TestMVC/Controllers/BlogController.cs
using AutoMapper;
using BLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestMVC.ViewModel;

namespace TestMVC.Controllers
{
    public class BlogController : Controller
    {

        public IDataService DataService { get; set; }

        public BlogController(IDataService dataService)
        {
            DataService = dataService;
        }
        //
        // GET: /Blog/
        public ActionResult Index()
        {
            var blogs = DataService.GetAllBlogs();
            var blogsVM = Mapper.Map<IList<GetBlogVM>>(blogs);
            return View(blogsVM);
        }
        
        //
        // GET: /Blog/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Blog/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateBlogVM model)
        {
            try
            {
                if (ModelState.IsValid == false) return View(model);

                var blogDTO = Mapper.Map<BlogDTO>(model);
                DataService.CreateBlog(blogDTO);

                return RedirectToAction("Index");                
            }
            catch
            {
                return View();
            }
        }
    }
}

TestMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TestMVC/Controllers/PostController.cs
using AutoMapper;
using BLL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using TestMVC.ViewModel;


namespace TestMVC.Controllers
{
    public class PostController : Controller
    {
        public IDataService DataService { get; set; }

        public PostController(IDataService dataService)
        {
            DataService = dataService;
        }

        //
        // GET: /Post/
        public ActionResult Index(int blogId)
        {
            var posts = DataService.GetPostByBlog(blogId);
            var postsVM = Mapper.Map<IList<GetPostVM>>(posts);
            return View(postsVM);
        }

        public ActionResult Create(int blogId)
        {
            //validate the passed blogId exists in DB first
            return View();
        }

        //
        // POST: /Blog/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int blogId, CreatePostVM model)
        {
            try
            {
                if (ModelState.IsValid == false) return View(model);

                var postDTO = Mapper.Map<PostDTO>(model);
                postDTO.BlogId = blogId;
                DataService.CreatePost(postDTO);

                return RedirectToAction("Index", "Post", new { @blogId = blogId });
            }
            catch(Exception e)
            {
                return View();
            }
        }
	}
}

TestMVC/Views/Blog/Create.cshtml
@model TestMVC.ViewModel.CreateBlogVM

@{
    ViewBag.Title = "Add Blog";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <br />
        <h4>Create Blog</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Blogs", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TestMVC/Views/Blog/Index.cshtml
@model IEnumerable<TestMVC.ViewModel.GetBlogVM>

@{
    ViewBag.Title = "Blogs";
}

<h2>Blogs</h2>
<br />
<p>
    @Html.ActionLink("Add New Blog..", "Create", "Blog", null,  new { @class = "btn btn-default" })
</p>
<br />

<div class="container">
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>
            <input type="text" id="txtSearchBlog" placeholder="Search blog" class="form-control"/>
        </div>
    </div>
</div>
<br />
<table class="table table-striped">
    <tr>       
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreationDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr class="tbtrSearchBlog">
        <td>            
            @Html.ActionLink(item.Title, "Index", "Post", new { blogId = item.BlogId }, new { @class = "btn btn-primary" })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreationDate)
        </td>        
    </tr>
}
</table>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    
    <script>
        $(document).ready(function () {
            function contains(txtOne, txtTwo)
            {
                if (txtOne.indexOf(txtTwo) != -1) return true;                
            }
            $("#txtSearchBlog").keyup(function () {
                var searchTxt = $("#txtSearchBlog").val().toLowerCase();
                $(".tbtrSearchBlog").each(function () {
                    if (!contains($(this).text().toLowerCase(), searchTxt)) {
                        $(this).hide();
                    }
                    else {
                        $(this).show();
                    }
                });
            });
        });
    </script>
}

TestMVC/Views/Blog/Search.cshtml
@model TestMVC.ViewModel.SearchBlogVM

@{
    ViewBag.Title = "Search Blog";
}

<h2>Search Blogs</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Search Blogs</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EnterDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EnterDate)
                @Html.ValidationMessageFor(model => model.EnterDate)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default btnSearchBlog" />
            </div>
        </div>
    </div>
}

<br />
<br />


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        var url = '@Url.Action("DisplaySearchResult", "Blog")';
        var keywordTitle = $("#Title").val;
        var enterDate = $("#EnterDate").val;

        $('form').submit(function () {
            if (!$(this).valid()) {
                return false; // prevent the ajax call if validation errors
            }
            var form = $(this).serialize();
            $('#SearchResults').load(url, form);
            return false; // prevent the default submit action
        })
    </script>
}

TestMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>


<h4>Simple Blog Engine using ASP.net MVC using EntityFramework 6.0 Code first, MSSQL, MVC, MVVM & Dependancy Injection.</h4>

TestMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>Contact</h2>
<br />
<address>
    Marwa Ahmad<br />    
</address>

<address>
    <strong>e-mail:</strong>   <a href="mailto:marwa.ahmad8@gmail.com">marwa.ahmad8@gmail.com</a><br />
    
</address>

TestMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row">    
    <div class="col-md-4">
        <br />        
        <p>@Html.ActionLink("List blogs", "Index", "Blog", null, new { @class = "btn btn-default" })</p>
    </div>    
</div>

TestMVC/Views/Post/Create.cshtml
@model TestMVC.ViewModel.CreatePostVM

@{
    ViewBag.Title = "Add Post";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <br />
        <h4>Create Post</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content)
                @Html.ValidationMessageFor(model => model.Content)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Posts", "Index", "Post", new { blogId = Request.QueryString["blogId"] }, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TestMVC/Views/Post/Index.cshtml
@model IEnumerable<TestMVC.ViewModel.GetPostVM>

@{
    ViewBag.Title = "Posts";
}

<h2>Posts</h2>
<br />
<p>
    @Html.ActionLink("Add New Post..", "Create", "Post", new { blogId = Request.QueryString["blogId"] }, new { @class = "btn btn-default" })
</p>
<table class="table">
    <tr>        
        <th>
            @Html.DisplayNameFor(model => model.PostId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>        
    </tr>

@foreach (var item in Model) {
    <tr>        
        <td>
            @Html.DisplayFor(modelItem => item.PostId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>        
    </tr>
}

</table>

<div>
    @Html.ActionLink("Back to Blogs", "Index", "Blog")
</div>

TestMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Blog Engine</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Blog Engine", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Blog Engine</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>